version: '2'
services:
  rabbitmq:
    container_name: some-rabbitmq
    image: launcher.gcr.io/google/rabbitmq3
    environment:
      "RABBITMQ_ERLANG_COOKIE": "$RABBITMQ_ERLANG_COOKIE"
      "RABBITMQ_DEFAULT_USER": "$RABBITMQ_DEFAULT_USER"
      "RABBITMQ_DEFAULT_PASS": "$RABBITMQ_DEFAULT_PASS"
    ports:
      - '4369:4369'
      - '5671:5671'
      - '5672:5672'
      - '25672:25672'